yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Группа
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Добавление нового поста
    path('create/', views.post_create, name='post_create'),
    # Редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Добавление комментария
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    # лента подписок
    path('follow/', views.follow_index, name='follow_index'),
    # Подписаться
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписаться
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(template_name='users/signup.html'),
        name='signup'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # регистрация и авторизация
    path('auth/', include('users.urls', namespace='users')),

    # если нужного шаблона для /auth не нашлось в файле users.urls —
    # ищем совпадения в файле django.contrib.auth.urls
    path('auth/', include('django.contrib.auth.urls')),

    # раздел администратора
    path('admin/', admin.site.urls),

    path('about/', include('about.urls', namespace='about')),
    # обработчик для главной страницы ищем в urls.py приложения posts
    path("", include('posts.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">О технологиях</a>
  </p>
  <p class="m-0 text-dark text-center ">
    Асоциальная сеть <span style="color:red">Ya</span>tube © {% now "Y" %}, все права защищены.
  </p>

</footer>

yatube/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">

      <span style="color:red">Ya</span>tube
    </a>

    {% comment %}
    Меню - список пунктов со стандартными классами Bootsrap.
    Класс nav-pills нужен для выделения активных пунктов
    {% endcomment %}
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
        href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
        href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
        href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'logout' %}active{% endif %}"
        href="{% url 'logout' %}">Выйти</a>
      </li>
      <li>
        <a class="nav-link link-blue {% if view_name  == 'profile/{{ user.username }}' %}active{% endif %}"
        href="{% url 'users:login' %}">Пользователь: {{ user.username }}</a>
      <li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
        href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
        href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
      {% endwith %}
    </ul>
    {# Конец добавленого в спринте #}
  </div>
</nav>

yatube/templates/includes/single_post.html
{% load thumbnail %}

<!-- Блок поста -->

<div class="card mb-3 mt-1 shadow-sm">
  <div class="card-body">

    <p class="card-text">
      <a href="{% url 'posts:profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>

      {% if post.group is not None %}
        <a href="{% url 'posts:group_list' post.group.slug %}">
          <strong class="d-block text-gray-dark">[{{ post.group }}]</strong>
        </a>
      {% endif %}

      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <a><img class="card-img my-2" src="{{ im.url }}"></a>
      {% endthumbnail %}

      <!-- Текст поста -->
      <p>
      {{ post|linebreaksbr }}
      </p>
    </p>

    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group ">

        {% block comment %}
        <a class="btn btn-sm text-muted" href="{% url 'posts:post_detail' post.id %}" role="button">
          Подробная информация
        </a>
        {% endblock %}

        {% if post.author == request.user %}
          {% block edit %}
          <a class="btn btn-sm text-muted" href="{% url 'posts:post_detail' post.id %}edit" role="button">
            Редактировать
          </a>
          {% endblock %}
        {% endif %}

      </div>
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>

<!-- Блок комментариев -->

<!-- Форма для отправки комментария -->

{% if available_for_comment %}

{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-1">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

<!-- Список оставленных комментариев -->

{% for comment in post.comments.all %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         <small class="text-muted">{{ comment.created }}</small>
        </p>
        <p>
         {{ comment.text|linebreaksbr }}
        </p>
      </div>
    </div>
{% endfor %}
{% endif %}

yatube/templates/includes/user_card.html
<div class="card">
  <div class="card-body">
    <div class="h2">
      <!-- Имя автора -->
      {{ profile.get_full_name }}

    </div>
    <div class="h3 text-muted">
      <!-- username автора -->
      @{{ profile }}
    </div>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <div class="h6 text-muted">
        Подписчиков: {{ profile.following.all|length }} <br>
        Подписан: {{ profile.follower.all|length }}
      </div>
    </li>
    <li class="list-group-item">
      <div class="h6 text-muted">
        <!-- Количество записей -->
        Записей: {{ posts|length }}
      </div>
    </li>
  </ul>
</div>

<!-- Подписка, отписка -->
{% if user.is_authenticated %}
  <!-- не показывать кнопку подписаться на себя -->
  {% if profile != request.user %}
  <div class="mb-5">
    <br>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' profile.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' profile.username %}" role="button"
      >
        Подписаться
      </a>
     {% endif %}
  </div>
  {% endif %}
{% endif %}