yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Группа
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Добавление нового поста
    path('create/', views.post_create, name='post_create'),
    # Редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Добавление комментария
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    # лента подписок
    path('follow/', views.follow_index, name='follow_index'),
    # Подписаться
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписаться
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # регистрация и авторизация
    path('auth/', include('users.urls', namespace='users')),

    # если нужного шаблона для /auth не нашлось в файле users.urls —
    # ищем совпадения в файле django.contrib.auth.urls
    path('auth/', include('django.contrib.auth.urls')),

    # раздел администратора
    path('admin/', admin.site.urls),

    path('about/', include('about.urls', namespace='about')),
    # обработчик для главной страницы ищем в urls.py приложения posts
    path("", include('posts.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import PubDateModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200, help_text="200 символов максимум",
    )
    slug = models.SlugField(unique=True,)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(PubDateModel):
    text = models.TextField()
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts",
    )
    group = models.ForeignKey(
        Group, models.SET_NULL, blank=True, null=True, related_name="posts",
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comments",
    )
    text = models.TextField()
    created = models.DateTimeField("date published", auto_now_add=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.text


class Follow(models.Model):
    # ссылка на объект пользователя, который подписывается
    user = models.ForeignKey(
        User, related_name="follower", on_delete=models.CASCADE,
    )
    # ссылка на объект пользователя, на которого подписываются
    author = models.ForeignKey(
        User, related_name="following", blank=True, null=True,
        on_delete=models.CASCADE,
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст',
            'group': 'Группа',
            'image': 'Изображение',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст'
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

POSTS_PER_PAGE = 10


def paginator(posts, request):
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20)
def index(request):
    posts = Post.objects.all()
    page_obj = paginator(posts, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    profile = get_object_or_404(User, username=username)
    posts = profile.posts.all()
    page_obj = paginator(posts, request)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
    ).filter(
        author__username=username,
    ).exists()

    context = {
        'profile': profile,
        'page_obj': page_obj,
        'posts': posts,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    # комментарии берутся в самом шаблоне post.comments.all
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'form': form,
        'available_for_comment': True,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form = post.save()
        return redirect('posts:profile', username=request.user.username)

    context = {
        'form': form,
        'is_edit': False,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post.pk)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        form = post.save()
        return redirect('posts:post_detail', post_id=post_id)

    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    # будут выведены посты авторов, на которых подписан текущий пользователь
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(posts, request)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # подписка
    following_author = get_object_or_404(User, username=username)
    if request.user != following_author:
        Follow.objects.get_or_create(
            user=request.user,
            author=following_author,
        )
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    # отписка
    Follow.objects.filter(
        user=request.user
    ).filter(
        author__username=username,
    ).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Создание нового поста
  {% endif %}
{% endblock %}

{% block content %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">

        <div class="card-header">
          {% if is_edit %}
            Редактирование поста
          {% else %}
            Новый пост
          {% endif %}
        </div>

        <div class="card-body">
          <form method="post" enctype="multipart/form-data" action="{% if is_edit %}{% url 'posts:post_edit' post.id %}{% else %}{% url 'posts:post_create' %}{% endif%}">
            <input type="hidden" name="csrfmiddlewaretoken">

            {% csrf_token %}

            <div class="form-group row my-3 p-3">
              <label for="form.text.id_for_label">
                Текст поста
                <span class="required text-danger" >*</span>
              </label>
              <p>{{ form.text }}</p>
              <small id="id_text-help" class="form-text text-muted">
                Текст
              </small>
            </div>

            <div class="form-group row my-3 p-3">
                <label for="{{ form.group.id_for_label }}">
                  Группа
                </label>
                  <p>{{ form.group }}</p>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
            </div>

            <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
            </div>

            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}Лента подписок{% endblock %}
{% block header %}Лента подписок{% endblock %}
{% block content %}



    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
    {% include "includes/single_post.html" %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  

    {% include "posts/includes/paginator.html" %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block header %}
  {{ group.title }}
{% endblock %}

{% block content %}
    <p>
        {{ group.description }}
    </p>
    {% for post in page_obj %}
    {% include "includes/single_post.html" %}
    {% if not forloop.last %}<hr>{% endif %}
    {% empty %}
    <li>В группе еще нет постов ╮( ˘ ､ ˘ )╭</li>
    {% endfor %}

    {% include "posts/includes/paginator.html" %}

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}

{% block title %}
  Профиль пользователя {{ profile.get_full_name }} | Yatube
{% endblock %}

{% block content %}
<main role="main" class="container">
  <div class="row">

    <div class="col-md-12">
      {% include "includes/single_post.html" %}
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ profile.get_full_name }} {% endblock %} | Yatube

{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      {% include "includes/user_card.html" %}
    </div>

    <div class="col-md-9">
      <!-- Начало блока с постами -->
      {% for post in page_obj %}
      {% include "includes/single_post.html" %}
      {% endfor %}

      <!-- Здесь постраничная навигация паджинатора -->
      {% include "posts/includes/paginator.html" %}
    </div>
  </div>
</main>
{% endblock %}